# Generated by Django 3.1.5 on 2021-01-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lec',
            name='duration',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lec',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
