# Generated by Django 3.1.2 on 2020-11-02 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='pr_id',
            new_name='pi_id',
        ),
        migrations.RemoveField(
            model_name='pay',
            name='process',
        ),
        migrations.AlterField(
            model_name='pay',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
