# Generated by Django 3.1.7 on 2021-03-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('Address1', models.CharField(max_length=900)),
                ('Address2', models.CharField(blank=True, max_length=900, null=True)),
                ('Zip', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('DOB', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=500)),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
