# Generated by Django 3.1.2 on 2020-10-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_useradd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='address',
        ),
        migrations.RemoveField(
            model_name='useradd',
            name='std',
        ),
        migrations.RemoveField(
            model_name='useradd',
            name='upload',
        ),
    ]
